
#define SYSTEM_STRUCTID_UNDEFINED	0
#define SYSTEM_STRUCTID_SHEET		1
#define SYSTEM_STRUCTID_FIFO32		2
#define SYSTEM_STRUCTID_TEXTBOX		3
#define SYSTEM_STRUCTID_CONSOLE		4
#define SYSTEM_STRUCTID_FLOPPYDISK	5
#define SYSTEM_STRUCTID_FILE		6

